services:
  mysql:
    image: mysql:9
    container_name: mysql-db
    environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: testing
       MYSQL_USER: user
       MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node:
    build: .
    container_name: node-app
    ports:
     - "3000:3000"
    depends_on:
     - mysql
    command: npx jest player.test.js   
    volumes:
     - .:/app

volumes:
  mysql-data:
    driver: local

